# -*- coding: utf-8 -*-
"""Múltimidia/Realidade-Virtual.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Dr5SPRjRWoob20IB3vME5LNLN0u2kaLo

### 💗 Script para geração de frases/palavras para friendship Bracelets da Taylor Swift
"""

!pip install openai
!pip install langchain
!pip install langchain-openai

import os
os.environ['OPENAI_API_KEY'] = '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'

from langchain.chains import LLMChain
from langchain.prompts import PromptTemplate
from langchain_openai import OpenAI

llm = OpenAI()
prompt = PromptTemplate(
    input_variables=["music"],
    template="Generate a simple prompt (1000 characters) to generate words that reference Taylor swifit's songs: {music}.",
)
chain = LLMChain(llm=llm, prompt=prompt)

music = "Fever dream high in the quiet of the night"

output = chain.invoke({"music": music})

parsed_result = chain.invoke(output) # The result is a structured object
print(parsed_result)

from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

prompt = ChatPromptTemplate.from_template("Generate a simple prompt (1000 characters) to generate words that reference Taylor swifit's songs: {music}.")
model = ChatOpenAI(model="gpt-4")
output_parser = StrOutputParser()

chain = prompt | model | output_parser

chain.invoke({"music": "Fever dream high in the quiet of the night"})